---
version: "3.9"

services:
  postgres:
    image: postgres:16.2-alpine
    restart: always
    ports:
      - "${DB_FORWARD_PORT:-5432}:5432"
    volumes:
      - "./database/data:/var/lib/postgresql/data:cached"
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
